### ISSUE TITLE
Rift Wizard 2 

### ISSUE THREAD

**Issue by Rogerbanger666** [apollovy/rift-wizard-mod-scale#1]
Works great. Any chance of doing the same for RW2?

**Comment by apollovy** [comment]
Hey. It works great with RW2 too :)

**Comment by Rogerbanger666** [comment]
It worked great for RW1 but the game won't start when I use for RW2. Do I need to change anything to make it applicable to RW2?

**Comment by apollovy** [comment]
That's strange: before closing the issue, I specifically checked, that rw2 runs and works with the mod. The instructions are the same as for rw1. I had an old save in rw2 that's wasn't able to load. I deleted the save and things got great again!Kind regards,Yury Apollov3 сент. 2024 г., в 12:27, Rogerbanger666 ***@***.***> написал(а):﻿
It worked great for RW1 but the game won't start when I use for RW2. Do I need to change anything to make it applicable to RW2?

**Comment by Rogerbanger666** [comment]
No worries, I think it's something to do with I'm running on MacBook via Parallels. I managed to workaround with Borderless windows program :)
